name: Update Cookies Workflow

on:
  schedule:
    - cron: '0 6 * * *'  # example: every day at 6 AM UTC
  push:
    branches:
      - main

jobs:
  update-cookies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo (optional)
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
         pip install playwright
         playwright install

      - name: Install xvfb (virtual display server)
        run: sudo apt-get update && sudo apt-get install -y xvfb
        
      - name: Clone target repo with cookies.enc
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          TARGET_REPO: frozenflow/ytdownloader_backend
        run: |
          git clone https://x-access-token:${TOKEN}@github.com/${TARGET_REPO}.git ytdownloader_backend

      - name: Decrypt cookies.enc from target repo
        run: |
          openssl enc -d -aes-256-cbc -pbkdf2 -in ytdownloader_backend/cookies.enc -out ytdownloader_backend/cookies.txt -pass pass:"${{ secrets.COOKIE_KEY }}"

      - name: Copy cookies.txt to root
        run: cp ytdownloader_backend/cookies.txt .

      - name: Run your python script with cookies.txt path
        run: xvfb-run python3 spoof.py

      - name: Encrypt cookies.txt back to cookies.enc
        run: |
          openssl enc -aes-256-cbc -pbkdf2 -salt -in cookies.txt -out ytdownloader_backend/cookies.enc -pass pass:"${{ secrets.COOKIE_KEY }}"

      - name: Commit and push updated cookies.enc
        working-directory: ytdownloader_backend
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add cookies.enc
          git commit -m "Update cookies.enc via workflow" || echo "No changes"
          git push origin main
